[build]
  publish = "netlify"

[[edge_functions]]
  function = "add-item"
  path = "/add-item"

[[edge_functions]]
  function = "get-items"
  path = "/get-items"

[[edge_functions]]
  function = "update-item"
  path = "/update-item"

[[edge_functions]]
  function = "delete-item"
  path = "/delete-item"

[[edge_functions]]
  function = "get-categories"
  path = "/get-categories"

[[edge_functions]]
  function = "add-category"
  path = "/add-category"

[[edge_functions]]
  function = "update-category"
  path = "/update-category"

[[edge_functions]]
  function = "delete-category"
  path = "/delete-category"

[[edge_functions]]
  function = "get-bags"
  path = "/get-bags"

[[edge_functions]]
  function = "get-inventories"
  path = "/get-inventories"

[[edge_functions]]
  function = "update-credits"
  path = "/update-credits"